/* Auto-generated header file */
/* Extracted struct definitions and dependencies */

#ifndef _EP_SOCK_H
#define _EP_SOCK_H


/* Forward declarations */
struct _ddebug;
struct aa_dfa;
struct aa_label;
struct aa_loaddata;
struct aa_net_compat;
struct aa_ns;
struct aa_policydb;
struct aa_profile;
struct aa_proxy;
struct ack_sample;
struct address_space;
struct address_space_operations;
struct affinity_context;
struct anon_vma;
struct anon_vma_name;
struct arch_uprobe;
struct array_buffer;
struct assoc_array_ptr;
struct atomic64_t;
struct attribute;
struct attribute_group;
struct audit_names;
struct autogroup;
struct badblocks;
struct balance_callback;
struct bdev_handle;
struct bdi_writeback;
struct bin_attribute;
struct binfmt_misc;
struct bio;
struct bio_alloc_cache;
struct bio_crypt_ctx;
struct bio_list;
struct bio_set;
struct bio_vec;
struct blk_crypto_key;
struct blk_crypto_keyslot;
struct blk_crypto_profile;
struct blk_flush_queue;
struct blk_independent_access_ranges;
struct blk_integrity_iter;
struct blk_integrity_profile;
struct blk_mq_alloc_data;
struct blk_mq_ctx;
struct blk_mq_ctxs;
struct blk_mq_debugfs_attr;
struct blk_mq_hw_ctx;
struct blk_mq_ops;
struct blk_mq_queue_data;
struct blk_mq_tag_set;
struct blk_mq_tags;
struct blk_plug;
struct blk_queue_stats;
struct blk_trace;
struct blk_zone;
struct blkcg;
struct blkcg_gq;
struct blkcg_policy_data;
struct blkg_iostat_set;
struct blkg_policy_data;
struct block_device_operations;
union bpf_attr;
struct bpf_cgroup_storage_map;
struct bpf_ctx_arg_aux;
struct bpf_func_info;
struct bpf_func_info_aux;
struct bpf_func_proto;
struct bpf_func_state;
struct bpf_insn;
struct bpf_insn_access_aux;
struct bpf_insn_aux_data;
struct bpf_iter_aux_info;
struct bpf_iter_seq_info;
struct bpf_jit_poke_descriptor;
struct bpf_jmp_history_entry;
struct bpf_kfunc_btf_tab;
struct bpf_kfunc_desc_tab;
struct bpf_line_info;
struct bpf_local_storage;
struct bpf_local_storage_data;
struct bpf_local_storage_map;
struct bpf_local_storage_map_bucket;
struct bpf_map;
struct bpf_map_ops;
struct bpf_mem_cache;
struct bpf_mem_caches;
struct bpf_offload_dev;
struct bpf_prog;
struct bpf_prog_array;
struct bpf_prog_aux;
struct bpf_prog_offload;
struct bpf_prog_offload_ops;
struct bpf_prog_ops;
struct bpf_prog_stats;
struct bpf_raw_event_map;
struct bpf_reference_state;
struct bpf_reg_state;
struct bpf_run_ctx;
struct bpf_stack_state;
struct bpf_tramp_image;
struct bpf_trampoline;
struct bpf_verifier_env;
struct bpf_verifier_log;
struct bpf_verifier_ops;
struct bpf_verifier_stack_elem;
struct bpf_verifier_state;
struct bpf_verifier_state_list;
struct btf;
struct btf_id_dtor_kfunc_tab;
struct btf_id_set8;
struct btf_kfunc_set_tab;
struct btf_mod_pair;
struct btf_record;
struct btf_struct_meta;
struct btf_struct_metas;
struct btf_type;
struct bucket_table;
struct buffer_data_page;
struct buffer_page;
struct bug_entry;
struct callback_head;
struct can_dev_rcv_lists;
struct can_pkg_stats;
struct can_rcv_lists_stats;
struct capture_control;
struct cdrom_device_info;
struct cdrom_device_ops;
struct cdrom_mcn;
struct cdrom_multisession;
struct cfs_rq;
struct cftype;
struct cgroup;
struct cgroup_namespace;
struct cgroup_rstat_cpu;
struct cgroup_subsys;
struct cgroup_subsys_state;
struct cgroup_taskset;
struct compact_control;
struct compat_robust_list_head;
struct completion;
struct cond_snapshot;
struct core_vma_metadata;
struct coredump_params;
struct cpu_stop_done;
struct cpudl_item;
struct cpuidle_device;
struct cpuidle_device_kobj;
struct cpuidle_driver;
struct cpuidle_driver_kobj;
struct cpuidle_state;
struct cpuidle_state_kobj;
struct cpuidle_state_usage;
struct cpumask;
struct cred;
struct crypto_alg;
struct crypto_instance;
struct crypto_shash;
struct crypto_skcipher;
struct crypto_template;
struct crypto_tfm;
struct crypto_type;
struct css_set;
struct ctl_dir;
struct ctl_node;
struct ctl_table;
struct ctl_table_header;
struct ctl_table_poll;
struct ctl_table_root;
struct ctl_table_set;
struct ctx_rq_wait;
struct ddebug_class_map;
struct delayed_call;
struct dentry;
struct dentry_operations;
struct desc_struct;
struct dev_pagemap;
struct dev_pagemap_ops;
struct dir_context;
struct disk_events;
struct dst_entry;
struct dst_metrics;
struct dst_ops;
struct elevator_queue;
struct elevator_type;
struct elf64_shdr;
struct elf64_sym;
struct elv_fs_entry;
struct em_perf_domain;
struct em_perf_state;
struct error_injection_entry;
struct event_filter;
struct event_subsystem;
struct eventfs_attr;
struct eventfs_entry;
struct eventfs_inode;
struct exception_table_entry;
struct fasync_struct;
struct fdtable;
struct fib6_info;
struct fib6_node;
struct fib6_table;
struct fib_info;
struct fib_lookup_arg;
struct fib_nh_exception;
struct fib_notifier_ops;
struct fib_rule;
struct fib_rule_hdr;
struct fib_rules_ops;
struct fib_table;
struct fiemap_extent;
struct fiemap_extent_info;
struct file;
struct file_lock;
struct file_lock_context;
struct file_lock_operations;
struct file_operations;
struct file_ra_state;
struct fileattr;
struct filename;
struct files_struct;
struct filter_pred;
struct flowi;
struct fnhe_hash_bucket;
struct folio;
struct fpstate;
struct fqdir;
struct fs_pin;
struct fs_struct;
struct fscrypt_direct_key;
struct fscrypt_inode_info;
struct fscrypt_master_key;
struct fscrypt_mode;
struct fsnotify_mark_connector;
struct fsverity_hash_alg;
struct fsverity_info;
struct ftrace_event_field;
struct ftrace_hash;
struct ftrace_ops;
struct ftrace_ops_hash;
struct ftrace_regs;
struct ftrace_ret_stack;
struct futex_pi_state;
struct gendisk;
struct group_info;
struct hd_geometry;
struct hlist_bl_node;
struct hlist_head;
struct hlist_node;
struct hlist_nulls_node;
struct hrtimer;
struct hrtimer_clock_base;
struct hrtimer_cpu_base;
struct iattr;
struct icmp_mib;
struct icmpmsg_mib;
struct icmpv6_mib;
struct icmpv6msg_mib;
struct in6_addr;
struct inet_bind_hashbucket;
struct inet_ehash_bucket;
struct inet_frag_queue;
struct inet_frags;
struct inet_hashinfo;
struct inet_listen_hashbucket;
struct inet_peer_base;
struct inode;
struct inode_operations;
struct io_bitmap;
struct io_comp_batch;
struct io_context;
struct io_cq;
struct io_uring_cmd;
struct io_uring_sqe;
struct io_uring_task;
struct io_wq;
struct io_wq_hash;
struct io_wq_work;
struct io_wq_work_node;
struct ioam6_pernet_data;
struct iov_iter;
struct ip_conntrack_stat;
struct ip_ra_chain;
struct ipstats_mib;
struct ipv4_devconf;
struct ipv6_devconf;
struct irq_work;
struct jump_entry;
struct kernel_param;
struct kernel_param_ops;
struct kernel_pkey_params;
struct kernel_pkey_query;
struct kernel_siginfo;
struct kernel_symbol;
struct kernfs_iattrs;
struct kernfs_node;
struct kernfs_open_file;
struct kernfs_open_node;
struct kernfs_ops;
struct kernfs_root;
struct kernfs_syscall_ops;
struct key;
struct key_match_data;
union key_payload;
struct key_preparsed_payload;
struct key_restriction;
struct key_tag;
struct key_type;
struct key_user;
struct kiocb;
struct kioctx;
struct kioctx_cpu;
struct klp_modinfo;
struct kmem_cache;
struct kmem_cache_cpu;
struct kmem_cache_node;
struct kobj_ns_type_operations;
struct kobj_type;
struct kobj_uevent_env;
struct kobject;
struct kset;
struct kset_uevent_ops;
struct kstat;
struct kthread_work;
struct kthread_worker;
struct latency_bucket;
struct ldt_struct;
struct linux_binprm;
struct linux_mib;
struct linux_tls_mib;
struct linux_xfrm_mib;
struct list_head;
struct llist_head;
struct llist_node;
struct lock_class_key;
struct lock_manager_operations;
union lower_chunk;
struct lru_gen_mm_walk;
struct lruvec;
struct lwtunnel_state;
struct math_emu_info;
struct mempolicy;
struct mm_struct;
struct mnt_idmap;
struct mnt_namespace;
struct mnt_pcp;
struct mod_kallsyms;
struct module;
struct module_attribute;
struct module_kobject;
struct module_notes_attrs;
struct module_param_attrs;
struct module_sect_attrs;
struct mount;
struct mountpoint;
struct mpls_route;
struct mptcp_mib;
struct msghdr;
struct nameidata;
struct napi_struct;
struct neigh_hash_table;
struct neigh_ops;
struct neigh_parms;
struct neigh_statistics;
struct neigh_table;
struct neighbour;
struct net;
struct net_generic;
struct netlbl_lsm_cache;
struct netlbl_lsm_catmap;
struct netlink_ext_ack;
struct netns_ipvs;
struct nexthop;
struct nf_conn;
struct nf_conntrack_expect;
struct nf_conntrack_helper;
struct nf_ct_event;
struct nf_ct_event_notifier;
struct nf_ct_ext;
struct nf_exp_event;
struct nf_flow_table_stat;
struct nf_hook_entries;
struct nf_hook_state;
struct nf_logger;
struct nf_loginfo;
struct nfs4_lock_state;
struct nh_group;
struct nh_grp_entry;
struct nh_res_table;
struct nla_policy;
struct nlattr;
struct nlm_lockowner;
struct notification;
struct notifier_block;
struct ns_common;
struct nsproxy;
struct nsset;
struct numa_group;
struct obj_cgroup;
struct offset_ctx;
struct packet_command;
struct page;
struct page_pool_recycle_stats;
struct path;
struct per_cpu_pages;
struct per_cpu_zonestat;
struct percpu_cluster;
struct percpu_counter;
struct percpu_ref;
struct percpu_ref_data;
struct perf_domain;
struct perf_event_context;
struct pid;
struct pid_namespace;
struct pipe_buf_operations;
struct pipe_buffer;
struct pipe_inode_info;
struct pmd_t;
struct pneigh_entry;
struct poll_table_struct;
struct pool_workqueue;
struct posix_acl;
struct pr_held_reservation;
struct pr_keys;
struct pr_ops;
struct proc_dir_entry;
struct proc_ns_operations;
struct prog_entry;
struct prot_inuse;
struct proto;
struct proto_ops;
struct psi_group;
struct psi_group_cpu;
struct pt_regs;
struct pte_t;
struct pud_t;
struct qstr;
struct rate_sample;
struct rb_node;
struct rchan;
struct rchan_buf;
struct rchan_callbacks;
struct rcu_node;
struct readahead_control;
struct reclaim_state;
struct regex;
struct request;
struct request_queue;
struct request_sock;
struct request_sock_ops;
struct restart_block;
struct return_instance;
struct rhash_head;
struct rhash_lock_head;
struct rhashtable;
struct rhashtable_compare_arg;
struct ring_buffer_event;
struct ring_buffer_iter;
struct ring_buffer_per_cpu;
struct robust_list;
struct robust_list_head;
struct root_domain;
struct rq;
struct rq_flags;
struct rq_qos;
struct rq_qos_ops;
struct rseq;
struct rt6_exception_bucket;
struct rt6_info;
struct rt6_statistics;
struct rt_mutex_base;
struct rt_mutex_waiter;
struct rtable;
struct rtattr;
struct saved;
struct saved_syn;
struct sbitmap_word;
struct sbq_wait_state;
struct sched_class;
struct sched_dl_entity;
struct sched_domain;
struct sched_domain_shared;
struct sched_entity;
struct sched_group;
struct sched_group_capacity;
struct sched_rt_entity;
struct scsi_sense_hdr;
struct sctp_mib;
struct seccomp_filter;
struct seg6_pernet_data;
struct sem_undo_list;
struct seq_file;
struct seq_operations;
struct sighand_struct;
struct sk_buff;
struct sk_filter;
struct sk_msg;
struct sk_psock;
struct skb_ext;
struct slab;
struct smack_known;
struct smc_stats;
struct smc_stats_rsn;
struct sock;
struct sock_filter;
struct sock_fprog_kern;
struct sock_reuseport;
struct sockaddr;
struct socket;
struct spinlock;
struct srcu_data;
struct srcu_node;
struct srcu_struct;
struct srcu_usage;
struct static_call_key;
struct static_call_mod;
struct static_call_site;
struct static_key_mod;
struct strparser;
struct swap_cluster_info;
struct swap_info_struct;
struct swap_iocb;
struct sysfs_ops;
struct table_header;
struct task_delay_info;
struct task_group;
struct task_struct;
union tcp_cc_info;
struct tcp_congestion_ops;
struct tcp_fastopen_context;
struct tcp_mib;
struct throtl_data;
struct throtl_service_queue;
struct time_namespace;
struct timer_list;
struct timer_rand_state;
struct timewait_sock_ops;
struct trace_array;
struct trace_array_cpu;
struct trace_buffer;
struct trace_entry;
struct trace_eval_map;
struct trace_event;
struct trace_event_call;
struct trace_event_class;
struct trace_event_fields;
struct trace_event_file;
struct trace_event_functions;
struct trace_func_repeats;
struct trace_iterator;
struct trace_option_dentry;
struct trace_options;
struct trace_pid_list;
struct trace_subsystem_dir;
struct tracepoint;
struct tracepoint_func;
struct tracer;
struct tracer_flags;
struct tracer_opt;
struct ubuf_info;
struct ucounts;
struct udp_hslot;
struct udp_mib;
struct udp_table;
struct uevent_sock;
struct uncached_list;
union upper_chunk;
struct uprobe;
struct uprobe_consumer;
struct uprobe_task;
struct uprobe_xol_ops;
struct user_event_mm;
struct user_namespace;
struct user_struct;
struct userfaultfd_ctx;
struct uts_namespace;
struct vdso_image;
struct vfsmount;
struct vm_area_struct;
struct vm_fault;
struct vm_operations_struct;
struct vm_special_mapping;
struct vm_struct;
struct vma_lock;
struct vma_numab_state;
struct wait_queue_entry;
struct wake_q_node;
struct watch;
struct watch_filter;
struct watch_list;
struct watch_queue;
struct work_struct;
struct worker;
struct worker_pool;
struct workqueue_attrs;
struct workqueue_struct;
struct wq_flusher;
struct writeback_control;
struct ww_acquire_ctx;
struct xol_area;
struct zone;

typedef short unsigned int __kernel_sa_family_t;
typedef __u32 __portpair;
typedef __u64 __addrpair;
struct assoc_array_ptr;
struct can_dev_rcv_lists;
struct can_pkg_stats;
struct can_rcv_lists_stats;
struct cpuidle_driver_kobj;
struct mpls_route;
struct netns_ipvs;
typedef struct {} netns_tracker;
struct nf_conntrack_helper;
struct nlm_lockowner;
struct request_sock_ops {
	int family;
	unsigned int obj_size;
	struct kmem_cache *slab;
	char *slab_name;
	int (*rtx_syn_ack)(const struct sock *, struct request_sock *);
	void (*send_ack)(const struct sock *, struct sk_buff *, struct request_sock *);
	void (*send_reset)(const struct sock *, struct sk_buff *);
	void (*destructor)(struct request_sock *);
	void (*syn_ack_timeout)(const struct request_sock *);
};
typedef __kernel_sa_family_t sa_family_t;
struct sctp_mib;
typedef struct {
	size_t written;
	size_t count;
	union {
		char *buf;
		void *data;
	} arg;
	int error;
} read_descriptor_t;
struct sk_filter {
	refcount_t refcnt;
	struct callback_head rcu;
	struct bpf_prog *prog;
};
struct sk_psock_progs {
	struct bpf_prog *msg_parser;
	struct bpf_prog *stream_parser;
	struct bpf_prog *stream_verdict;
	struct bpf_prog *skb_verdict;
};
typedef int (*sk_read_actor_t)(read_descriptor_t *, struct sk_buff *, unsigned int, size_t);
typedef int (*skb_read_actor_t)(struct sock *, struct sk_buff *);
struct smc_hashinfo;
struct smc_stats;
struct smc_stats_rsn;
struct sockaddr {
	sa_family_t sa_family;
	union {
		char sa_data_min[14];
		struct {
			struct {} __empty_sa_data;
			char sa_data[0];
		};
	};
};
struct sockaddr_in {
	__kernel_sa_family_t sin_family;
	__be16 sin_port;
	struct in_addr sin_addr;
	unsigned char __pad[8];
};
typedef enum {
	SS_FREE = 0,
	SS_UNCONNECTED = 1,
	SS_CONNECTING = 2,
	SS_CONNECTED = 3,
	SS_DISCONNECTING = 4,
} socket_state;
struct proto_ops {
	int family;
	struct module *owner;
	int (*release)(struct socket *);
	int (*bind)(struct socket *, struct sockaddr *, int);
	int (*connect)(struct socket *, struct sockaddr *, int, int);
	int (*socketpair)(struct socket *, struct socket *);
	int (*accept)(struct socket *, struct socket *, int, bool);
	int (*getname)(struct socket *, struct sockaddr *, int);
	__poll_t (*poll)(struct file *, struct socket *, struct poll_table_struct *);
	int (*ioctl)(struct socket *, unsigned int, long unsigned int);
	int (*compat_ioctl)(struct socket *, unsigned int, long unsigned int);
	int (*gettstamp)(struct socket *, void *, bool, bool);
	int (*listen)(struct socket *, int);
	int (*shutdown)(struct socket *, int);
	int (*setsockopt)(struct socket *, int, int, sockptr_t, unsigned int);
	int (*getsockopt)(struct socket *, int, int, char *, int *);
	void (*show_fdinfo)(struct seq_file *, struct socket *);
	int (*sendmsg)(struct socket *, struct msghdr *, size_t);
	int (*recvmsg)(struct socket *, struct msghdr *, size_t, int);
	int (*mmap)(struct file *, struct socket *, struct vm_area_struct *);
	ssize_t (*splice_read)(struct socket *, loff_t *, struct pipe_inode_info *, size_t, unsigned int);
	void (*splice_eof)(struct socket *);
	int (*set_peek_off)(struct sock *, int);
	int (*peek_len)(struct socket *);
	int (*read_sock)(struct sock *, read_descriptor_t *, sk_read_actor_t);
	int (*read_skb)(struct sock *, skb_read_actor_t);
	int (*sendmsg_locked)(struct sock *, struct msghdr *, size_t);
	int (*set_rcvlowat)(struct sock *, int);
};
struct strp_callbacks {
	int (*parse_msg)(struct strparser *, struct sk_buff *);
	void (*rcv_msg)(struct strparser *, struct sk_buff *);
	int (*read_sock)(struct strparser *, read_descriptor_t *, sk_read_actor_t);
	int (*read_sock_done)(struct strparser *, int);
	void (*abort_parser)(struct strparser *, int);
	void (*lock)(struct strparser *);
	void (*unlock)(struct strparser *);
};
struct strp_stats {
	long long unsigned int msgs;
	long long unsigned int bytes;
	unsigned int mem_fail;
	unsigned int need_more_hdr;
	unsigned int msg_too_big;
	unsigned int msg_timeouts;
	unsigned int bad_hdr_len;
};
struct timewait_sock_ops {
	struct kmem_cache *twsk_slab;
	char *twsk_slab_name;
	unsigned int twsk_obj_size;
	int (*twsk_unique)(struct sock *, struct sock *, void *);
	void (*twsk_destructor)(struct sock *);
};
struct sock_reuseport {
	struct callback_head rcu;
	u16 max_socks;
	u16 num_socks;
	u16 num_closed_socks;
	u16 incoming_cpu;
	unsigned int synq_overflow_ts;
	unsigned int reuseport_id;
	unsigned int bind_inany: 1;
	unsigned int has_conns: 1;
	struct bpf_prog *prog;
	struct sock *socks[0];
};
struct proto {
	void (*close)(struct sock *, long int);
	int (*pre_connect)(struct sock *, struct sockaddr *, int);
	int (*connect)(struct sock *, struct sockaddr *, int);
	int (*disconnect)(struct sock *, int);
	struct sock * (*accept)(struct sock *, int, int *, bool);
	int (*ioctl)(struct sock *, int, int *);
	int (*init)(struct sock *);
	void (*destroy)(struct sock *);
	void (*shutdown)(struct sock *, int);
	int (*setsockopt)(struct sock *, int, int, sockptr_t, unsigned int);
	int (*getsockopt)(struct sock *, int, int, char *, int *);
	void (*keepalive)(struct sock *, int);
	int (*compat_ioctl)(struct sock *, unsigned int, long unsigned int);
	int (*sendmsg)(struct sock *, struct msghdr *, size_t);
	int (*recvmsg)(struct sock *, struct msghdr *, size_t, int, int *);
	void (*splice_eof)(struct socket *);
	int (*bind)(struct sock *, struct sockaddr *, int);
	int (*bind_add)(struct sock *, struct sockaddr *, int);
	int (*backlog_rcv)(struct sock *, struct sk_buff *);
	bool (*bpf_bypass_getsockopt)(int, int);
	void (*release_cb)(struct sock *);
	int (*hash)(struct sock *);
	void (*unhash)(struct sock *);
	void (*rehash)(struct sock *);
	int (*get_port)(struct sock *, short unsigned int);
	void (*put_port)(struct sock *);
	int (*psock_update_sk_prot)(struct sock *, struct sk_psock *, bool);
	unsigned int inuse_idx;
	int (*forward_alloc_get)(const struct sock *);
	bool (*stream_memory_free)(const struct sock *, int);
	bool (*sock_is_readable)(struct sock *);
	void (*enter_memory_pressure)(struct sock *);
	void (*leave_memory_pressure)(struct sock *);
	atomic_long_t *memory_allocated;
	int *per_cpu_fw_alloc;
	struct percpu_counter *sockets_allocated;
	long unsigned int *memory_pressure;
	long int *sysctl_mem;
	int *sysctl_wmem;
	int *sysctl_rmem;
	u32 sysctl_wmem_offset;
	u32 sysctl_rmem_offset;
	int max_header;
	bool no_autobind;
	struct kmem_cache *slab;
	unsigned int obj_size;
	unsigned int ipv6_pinfo_offset;
	slab_flags_t slab_flags;
	unsigned int useroffset;
	unsigned int usersize;
	unsigned int *orphan_count;
	struct request_sock_ops *rsk_prot;
	struct timewait_sock_ops *twsk_prot;
	union {
		struct inet_hashinfo *hashinfo;
		struct udp_table *udp_table;
		struct raw_hashinfo *raw_hash;
		struct smc_hashinfo *smc_hash;
	} h;
	struct module *owner;
	char name[32];
	struct list_head node;
	int (*diag_destroy)(struct sock *, int);
};
struct sk_psock_work_state {
	u32 len;
	u32 off;
};
struct sock_cgroup_data {
	struct cgroup *cgroup;
	u32 classid;
	u16 prioidx;
};
struct sock_common {
	union {
		__addrpair skc_addrpair;
		struct {
			__be32 skc_daddr;
			__be32 skc_rcv_saddr;
		};
	};
	union {
		unsigned int skc_hash;
		__u16 skc_u16hashes[2];
	};
	union {
		__portpair skc_portpair;
		struct {
			__be16 skc_dport;
			__u16 skc_num;
		};
	};
	short unsigned int skc_family;
	volatile unsigned char skc_state;
	unsigned char skc_reuse: 4;
	unsigned char skc_reuseport: 1;
	unsigned char skc_ipv6only: 1;
	unsigned char skc_net_refcnt: 1;
	int skc_bound_dev_if;
	union {
		struct hlist_node skc_bind_node;
		struct hlist_node skc_portaddr_node;
	};
	struct proto *skc_prot;
	possible_net_t skc_net;
	struct in6_addr skc_v6_daddr;
	struct in6_addr skc_v6_rcv_saddr;
	atomic64_t skc_cookie;
	union {
		long unsigned int skc_flags;
		struct sock *skc_listener;
		struct inet_timewait_death_row *skc_tw_dr;
	};
	int skc_dontcopy_begin[0];
	union {
		struct hlist_node skc_node;
		struct hlist_nulls_node skc_nulls_node;
	};
	short unsigned int skc_tx_queue_mapping;
	short unsigned int skc_rx_queue_mapping;
	union {
		int skc_incoming_cpu;
		u32 skc_rcv_wnd;
		u32 skc_tw_rcv_nxt;
	};
	refcount_t skc_refcnt;
	int skc_dontcopy_end[0];
	union {
		u32 skc_rxhash;
		u32 skc_window_clamp;
		u32 skc_tw_snd_nxt;
	};
};
typedef u64 dma_addr_t;
typedef u64 netdev_features_t;
struct scatterlist {
	long unsigned int page_link;
	unsigned int offset;
	unsigned int length;
	dma_addr_t dma_address;
	unsigned int dma_length;
	unsigned int dma_flags;
};
struct sk_msg_sg {
	u32 start;
	u32 curr;
	u32 end;
	u32 size;
	u32 copybreak;
	long unsigned int copy[1];
	struct scatterlist data[19];
};
struct sk_msg {
	struct sk_msg_sg sg;
	void *data;
	void *data_end;
	u32 apply_bytes;
	u32 cork_bytes;
	u32 flags;
	struct sk_buff *skb;
	struct sock *sk_redir;
	struct sock *sk;
	struct list_head list;
};
struct request_sock {
	struct sock_common __req_common;
	struct request_sock *dl_next;
	u16 mss;
	u8 num_retrans;
	u8 syncookie: 1;
	u8 num_timeout: 7;
	u32 ts_recent;
	struct timer_list rsk_timer;
	const struct request_sock_ops *rsk_ops;
	struct sock *sk;
	struct saved_syn *saved_syn;
	u32 secid;
	u32 peer_secid;
	u32 timeout;
};
struct saved_syn {
	u32 mac_hdrlen;
	u32 network_hdrlen;
	u32 tcp_hdrlen;
	u8 data[0];
};
struct raw_hashinfo {
	spinlock_t lock;
	long: 64;
	long: 64;
	long: 64;
	long: 64;
	long: 64;
	long: 64;
	long: 64;
	struct hlist_head ht[256];
};
typedef struct {
	spinlock_t slock;
	int owned;
	wait_queue_head_t wq;
} socket_lock_t;
struct sock {
	struct sock_common __sk_common;
	struct dst_entry *sk_rx_dst;
	int sk_rx_dst_ifindex;
	u32 sk_rx_dst_cookie;
	socket_lock_t sk_lock;
	atomic_t sk_drops;
	int sk_rcvlowat;
	struct sk_buff_head sk_error_queue;
	struct sk_buff_head sk_receive_queue;
	struct {
		atomic_t rmem_alloc;
		int len;
		struct sk_buff *head;
		struct sk_buff *tail;
	} sk_backlog;
	int sk_forward_alloc;
	u32 sk_reserved_mem;
	unsigned int sk_ll_usec;
	unsigned int sk_napi_id;
	int sk_rcvbuf;
	int sk_disconnects;
	struct sk_filter *sk_filter;
	union {
		struct socket_wq *sk_wq;
		struct socket_wq *sk_wq_raw;
	};
	void *sk_policy[2];
	struct dst_entry *sk_dst_cache;
	atomic_t sk_omem_alloc;
	int sk_sndbuf;
	int sk_wmem_queued;
	refcount_t sk_wmem_alloc;
	long unsigned int sk_tsq_flags;
	union {
		struct sk_buff *sk_send_head;
		struct rb_root tcp_rtx_queue;
	};
	struct sk_buff_head sk_write_queue;
	__s32 sk_peek_off;
	int sk_write_pending;
	__u32 sk_dst_pending_confirm;
	u32 sk_pacing_status;
	long int sk_sndtimeo;
	struct timer_list sk_timer;
	__u32 sk_priority;
	__u32 sk_mark;
	long unsigned int sk_pacing_rate;
	long unsigned int sk_max_pacing_rate;
	struct page_frag sk_frag;
	netdev_features_t sk_route_caps;
	int sk_gso_type;
	unsigned int sk_gso_max_size;
	gfp_t sk_allocation;
	__u32 sk_txhash;
	u8 sk_gso_disabled: 1;
	u8 sk_kern_sock: 1;
	u8 sk_no_check_tx: 1;
	u8 sk_no_check_rx: 1;
	u8 sk_userlocks: 4;
	u8 sk_pacing_shift;
	u16 sk_type;
	u16 sk_protocol;
	u16 sk_gso_max_segs;
	long unsigned int sk_lingertime;
	struct proto *sk_prot_creator;
	rwlock_t sk_callback_lock;
	int sk_err;
	int sk_err_soft;
	u32 sk_ack_backlog;
	u32 sk_max_ack_backlog;
	kuid_t sk_uid;
	u8 sk_txrehash;
	u8 sk_prefer_busy_poll;
	u16 sk_busy_poll_budget;
	spinlock_t sk_peer_lock;
	int sk_bind_phc;
	struct pid *sk_peer_pid;
	const struct cred *sk_peer_cred;
	long int sk_rcvtimeo;
	ktime_t sk_stamp;
	atomic_t sk_tskey;
	atomic_t sk_zckey;
	u32 sk_tsflags;
	u8 sk_shutdown;
	u8 sk_clockid;
	u8 sk_txtime_deadline_mode: 1;
	u8 sk_txtime_report_errors: 1;
	u8 sk_txtime_unused: 6;
	bool sk_use_task_frag;
	struct socket *sk_socket;
	void *sk_user_data;
	void *sk_security;
	struct sock_cgroup_data sk_cgrp_data;
	void *sk_memcg;
	void (*sk_state_change)(struct sock *);
	void (*sk_data_ready)(struct sock *);
	void (*sk_write_space)(struct sock *);
	void (*sk_error_report)(struct sock *);
	int (*sk_backlog_rcv)(struct sock *, struct sk_buff *);
	struct sk_buff * (*sk_validate_xmit_skb)(struct sock *, void *, struct sk_buff *);
	void (*sk_destruct)(struct sock *);
	struct sock_reuseport *sk_reuseport_cb;
	struct bpf_local_storage *sk_bpf_storage;
	struct callback_head sk_rcu;
	netns_tracker ns_tracker;
};
struct socket_wq {
	wait_queue_head_t wait;
	struct fasync_struct *fasync_list;
	long unsigned int flags;
	struct callback_head rcu;
	long: 64;
};
struct socket {
	socket_state state;
	short int type;
	long unsigned int flags;
	struct file *file;
	struct sock *sk;
	const struct proto_ops *ops;
	long: 64;
	long: 64;
	long: 64;
	struct socket_wq wq;
};
struct strparser {
	struct sock *sk;
	u32 stopped: 1;
	u32 paused: 1;
	u32 aborted: 1;
	u32 interrupted: 1;
	u32 unrecov_intr: 1;
	struct sk_buff **skb_nextp;
	struct sk_buff *skb_head;
	unsigned int need_bytes;
	struct delayed_work msg_timer_work;
	struct work_struct work;
	struct strp_stats stats;
	struct strp_callbacks cb;
};
struct sk_psock {
	struct sock *sk;
	struct sock *sk_redir;
	u32 apply_bytes;
	u32 cork_bytes;
	u32 eval;
	bool redir_ingress;
	struct sk_msg *cork;
	struct sk_psock_progs progs;
	struct strparser strp;
	u32 copied_seq;
	u32 ingress_bytes;
	struct sk_buff_head ingress_skb;
	struct list_head ingress_msg;
	spinlock_t ingress_lock;
	long unsigned int state;
	struct list_head link;
	spinlock_t link_lock;
	refcount_t refcnt;
	void (*saved_unhash)(struct sock *);
	void (*saved_destroy)(struct sock *);
	void (*saved_close)(struct sock *, long int);
	void (*saved_write_space)(struct sock *);
	void (*saved_data_ready)(struct sock *);
	int (*psock_update_sk_prot)(struct sock *, struct sk_psock *, bool);
	struct proto *sk_proto;
	struct mutex work_mutex;
	struct sk_psock_work_state work_state;
	struct delayed_work work;
	struct sock *sk_pair;
	struct rcu_work rwork;
};
#endif /* _EP_SOCK_H */